server {
    listen 80;
    index index.html index.php;
    server_name localhost;
    root /var/www/html/public;
    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Rotas da API (MVC ou Legado)
    location /api/ {
        # Primeiro tenta encontrar arquivo físico na pasta public/api (se existir)
        # Se não, tenta encontrar na pasta legado /var/www/html/api/
        # Se nada for encontrado, manda para o Front Controller (index.php)
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # Se for o index.php, ele está em /public
        # Se for outro arquivo legado, ele está na raiz /var/www/html
        set $script_root /var/www/html/public;
        if (!-f /var/www/html/public$fastcgi_script_name) {
            set $script_root /var/www/html;
        }

        root $script_root;
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $script_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
